from fastapi import APIRouter, Depends, HTTPException, Request, UploadFile, File
from sqlalchemy.orm import Session
import uuid
import json
import logging

from ..core.config import settings
from ..core.db import get_db
from ..models import WorkOrder, WorkOrderAttachment
from ..integrations.odoo import odoo_client
from ..integrations.mq import event_bus
from ..integrations.obj_storage import obj_storage
from ..schemas.work_order import WorkOrderCreate, WorkOrderResponse
from ..schemas.auth import User
from ..schemas.webhook import StatusUpdateWebhook
from ..core.security import get_current_user
import redis

router = APIRouter(prefix="/mp/workorders", tags=["Work Orders"])
logger = logging.getLogger("bff")
redis_client = redis.Redis.from_url(settings.REDIS_URL)

@router.post("/customers", response_model=dict)
async def create_customer(customer: dict, db: Session = Depends(get_db)):
    """Create a new customer in Odoo."""
    try:
        vals = {
            'name': customer.get('name'),
            'phone': customer.get('phone'),
            'email': customer.get('email'),
            'customer_rank': 1
        }
        new_id = odoo_client.execute_kw('res.partner', 'create', [vals])
        return {"id": new_id, "name": vals['name'], "phone": vals['phone']}
    except Exception as e:
        logger.error(f"Customer create error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/{order_id}/upload")
async def upload_attachment(
    order_id: str,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # 1. Verify Work Order
    wo = db.query(WorkOrder).filter(WorkOrder.uuid == order_id).first()
    if not wo:
        raise HTTPException(status_code=404, detail="Work Order not found")
        
    # 2. Upload to MinIO
    try:
        contents = await file.read()
        object_name = f"work-orders/{order_id}/{file.filename}"
        file_url = obj_storage.put_bytes(object_name, contents, file.content_type)
        
        # 3. Record in DB
        attachment = WorkOrderAttachment(
            work_order_uuid=order_id,
            file_name=file.filename,
            file_url=file_url
        )
        db.add(attachment)
        db.commit()
        
        # 4. Notify (Audit/Odoo)
        event_bus.publish("evt:media_uploaded", {"uuid": order_id, "url": file_url})
        
        return {"filename": file.filename, "url": file_url}
        
    except Exception as e:
        logger.error(f"Upload failed: {e}")
        raise HTTPException(status_code=500, detail="Upload failed")

@router.post("/callback/status", tags=["Webhooks"])
async def update_work_order_status(payload: StatusUpdateWebhook, db: Session = Depends(get_db)):
    """Webhook called by Odoo when status changes."""
    # In prod, verify a shared secret signature here
    
    wo = db.query(WorkOrder).filter(WorkOrder.uuid == payload.bff_uuid).first()
    if not wo:
        logger.warning(f"Webhook: WorkOrder not found for UUID {payload.bff_uuid}")
        raise HTTPException(status_code=404, detail="Work Order not found")
        
    if wo.status != payload.new_status:
        logger.info(f"Syncing status for {wo.uuid}: {wo.status} -> {payload.new_status}")
        wo.status = payload.new_status
        db.commit()
        
        # Publish event
        event_bus.publish("evt:work_order_updated", {"uuid": wo.uuid, "status": wo.status})
        
    return {"status": "updated"}

@router.post("/", response_model=WorkOrderResponse)
async def create_work_order(
    order_in: WorkOrderCreate, 
    db: Session = Depends(get_db),
    current_user = Depends(get_current_user)
):
    # 1. Create in Odoo
    try:
        odoo_payload = {
            'name': 'New', # Will be auto-numbered
            'customer_id': order_in.customer_id,
            'vehicle_plate': order_in.vehicle_plate,
            'description': order_in.description,
            'bff_uuid': "pending", # We will update this later or generate here
        }
        
        # Add procedure_id if present
        if hasattr(order_in, 'procedure_id') and order_in.procedure_id:
             odoo_payload['procedure_id'] = order_in.procedure_id

        odoo_id = odoo_client.execute_kw('drmoto.work.order', 'create', [odoo_payload])
        
        if not odoo_id:
            raise HTTPException(status_code=500, detail="Failed to create WO in Odoo")
            
        # Get the name generated by Odoo
        name = odoo_client.execute_kw('drmoto.work.order', 'read', [[odoo_id], ['name']])[0]['name']
        
    except Exception as e:
        logger.error(f"Odoo create error: {e}")
        raise HTTPException(status_code=500, detail=f"Odoo Error: {str(e)}")

    # 2. Create in Local DB
    db_wo = WorkOrder(
        uuid=str(uuid.uuid4()),
        odoo_id=odoo_id,
        vehicle_plate=order_in.vehicle_plate,
        customer_id=str(order_in.customer_id),
        description=order_in.description,
        status="draft"
    )
    db.add(db_wo)
    db.commit()
    db.refresh(db_wo)
    
    # 3. Update Odoo with BFF UUID (for callbacks)
    try:
        odoo_client.execute_kw('drmoto.work.order', 'write', [[odoo_id], {'bff_uuid': db_wo.uuid}])
    except:
        pass # Non-critical

    return {
        "id": db_wo.uuid,
        "status": db_wo.status,
        "data": {
            "vehicle_plate": db_wo.vehicle_plate,
            "odoo_ref": name
        }
    }

@router.get("/customers/{partner_id}/vehicles")
async def get_customer_vehicles(partner_id: int, current_user = Depends(get_current_user)):
    """Get vehicles for a specific customer."""
    try:
        # Search drmoto.partner.vehicle where partner_id = partner_id
        domain = [['partner_id', '=', partner_id]]
        fields = ['id', 'license_plate', 'vehicle_id', 'vin', 'color']
        vehicles = odoo_client.execute_kw('drmoto.partner.vehicle', 'search_read', [domain], {'fields': fields})
        return vehicles
    except Exception as e:
        logger.error(f"Vehicle fetch error: {e}")
        raise HTTPException(status_code=500, detail="Failed to fetch vehicles")

@router.get("/customers/{partner_id}/orders")
async def get_customer_orders(partner_id: int, current_user = Depends(get_current_user)):
    """Get work orders for a specific customer from Odoo."""
    try:
        domain = [['customer_id', '=', partner_id]]
        fields = ['id', 'name', 'vehicle_plate', 'state', 'date_planned', 'amount_total', 'bff_uuid']
        orders = odoo_client.execute_kw('drmoto.work.order', 'search_read', [domain], {'fields': fields, 'order': 'create_date desc'})
        return orders
    except Exception as e:
        logger.error(f"Customer orders fetch error: {e}")
        raise HTTPException(status_code=500, detail="Failed to fetch orders")

@router.get("/search", response_model=list)
async def search_work_orders(plate: str, db: Session = Depends(get_db)):
    db_wos = db.query(WorkOrder).filter(WorkOrder.vehicle_plate == plate).all()
    results = []
    for wo in db_wos:
        results.append({
            "id": wo.uuid,
            "status": wo.status,
            "data": {
                "vehicle_plate": wo.vehicle_plate,
                "description": wo.description,
                "customer_id": wo.customer_id
            }
        })
    return results

@router.get("/{order_id}", response_model=WorkOrderResponse)
async def get_work_order(order_id: str, db: Session = Depends(get_db)):
    db_wo = db.query(WorkOrder).filter(WorkOrder.uuid == order_id).first()
    if not db_wo:
        raise HTTPException(status_code=404, detail="Work Order not found")
    
    # Fetch details from Odoo if possible
    odoo_details = {}
    if db_wo.odoo_id:
        try:
            fields = ['name', 'state', 'line_ids', 'amount_total', 'procedure_id']
            data = odoo_client.execute_kw('drmoto.work.order', 'read', [[db_wo.odoo_id], fields])
            if data:
                odoo_details = data[0]
                # If we have lines, fetch line details
                if odoo_details.get('line_ids'):
                    line_fields = ['product_id', 'name', 'quantity', 'price_unit', 'price_subtotal']
                    lines = odoo_client.execute_kw('drmoto.work.order.line', 'read', [odoo_details['line_ids'], line_fields])
                    odoo_details['lines'] = lines
        except Exception as e:
            logger.error(f"Failed to fetch Odoo details: {e}")

    return {
        "id": db_wo.uuid,
        "status": odoo_details.get('state', db_wo.status), # Prefer Odoo status
        "data": {
            "vehicle_plate": db_wo.vehicle_plate,
            "description": db_wo.description,
            "customer_id": db_wo.customer_id,
            "odoo": odoo_details
        }
    }

@router.post("/{order_id}/status")
async def update_status(order_id: str, status: str, db: Session = Depends(get_db), current_user = Depends(get_current_user)):
    """Update status in Odoo (and local)."""
    db_wo = db.query(WorkOrder).filter(WorkOrder.uuid == order_id).first()
    if not db_wo:
        raise HTTPException(status_code=404, detail="Work Order not found")
    
    # Map friendly status to Odoo status
    # draft -> confirmed -> diagnosing -> quoted -> in_progress -> ready -> done
    
    if not db_wo.odoo_id:
         raise HTTPException(status_code=400, detail="Not linked to Odoo")

    try:
        # We write to Odoo, and let webhook sync back OR sync manually here
        odoo_client.execute_kw('drmoto.work.order', 'write', [[db_wo.odoo_id], {'state': status}])
        
        # Manually sync local just in case
        db_wo.status = status
        db.commit()
        
        return {"status": "success", "new_state": status}
    except Exception as e:
         logger.error(f"Status update failed: {e}")
         raise HTTPException(status_code=500, detail=str(e))

@router.get("/active/list")
async def list_active_work_orders(db: Session = Depends(get_db), current_user = Depends(get_current_user)):
    """List active work orders for the dashboard."""
    # Active = not done, not cancel
    # We can fetch from local DB for speed, or Odoo for accuracy. 
    # Let's fetch from Odoo to show the power of integration.
    try:
        domain = [['state', 'not in', ['done', 'cancel', 'draft']]]
        fields = ['id', 'name', 'vehicle_plate', 'customer_id', 'state', 'date_planned', 'bff_uuid']
        orders = odoo_client.execute_kw('drmoto.work.order', 'search_read', [domain], {'fields': fields, 'limit': 20, 'order': 'date_planned desc'})
        return orders
    except Exception as e:
        logger.error(f"Active list fetch error: {e}")
        # Fallback to local DB?
        return []

@router.get("/customers/search")
async def search_customers(query: str = "", limit: int = 10):
    """Search customers in Odoo (Live proxy). No auth required for login/search."""
    try:
        # Search by name or phone
        domain = ['|', ['name', 'ilike', query], ['phone', 'ilike', query]] if query else []
        fields = ['id', 'name', 'phone', 'email', 'city']
        partners = odoo_client.execute_kw('res.partner', 'search_read', [domain], {'fields': fields, 'limit': limit})
        return partners
    except Exception as e:
        logger.error(f"Customer search error: {e}")
        raise HTTPException(status_code=500, detail="Failed to search customers")
